"""First migration

Revision ID: 0de90ea466a3
Revises: 
Create Date: 2024-06-05 15:17:16.095494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de90ea466a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patent',
    sa.Column('reg_number', sa.Integer(), nullable=False),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('appl_date', sa.Date(), nullable=True),
    sa.Column('author_raw', sa.String(length=150), nullable=True),
    sa.Column('owner_raw', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('actual', sa.Boolean(), nullable=True),
    sa.Column('class', sa.Integer(), nullable=True),
    sa.Column('subclass', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('reg_number')
    )
    op.create_table('person',
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('tax_number', sa.String(length=12), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('short_name', sa.String(length=80), nullable=True),
    sa.Column('legal_address', sa.String(), nullable=True),
    sa.Column('fact_address', sa.String(), nullable=True),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ownership',
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ownership')
    op.drop_table('person')
    op.drop_table('patent')
    # ### end Alembic commands ###
