"""Add filter and filtertaxnumber models, #8

Revision ID: 32c97c1aac39
Revises: 9d85321d9cb3
Create Date: 2024-06-16 10:27:32.820727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c97c1aac39'
down_revision: Union[str, None] = '9d85321d9cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=1000), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('tax_numbers_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_id'), 'filter', ['id'], unique=False)
    op.create_table('filtertaxnumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('tax_number', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filtertaxnumber_id'), 'filtertaxnumber', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filtertaxnumber_id'), table_name='filtertaxnumber')
    op.drop_table('filtertaxnumber')
    op.drop_index(op.f('ix_filter_id'), table_name='filter')
    op.drop_table('filter')
    # ### end Alembic commands ###
