"""Add country_code to patent

Revision ID: 9d85321d9cb3
Revises: c211cafd2cce
Create Date: 2024-06-15 11:15:54.012476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d85321d9cb3'
down_revision: Union[str, None] = 'c211cafd2cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patent', sa.Column('country_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patent', 'country_code')
    # ### end Alembic commands ###
