"""first migrate

Revision ID: c211cafd2cce
Revises: 
Create Date: 2024-06-13 16:00:25.589373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c211cafd2cce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patent',
    sa.Column('reg_number', sa.Integer(), nullable=False),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('appl_date', sa.Date(), nullable=True),
    sa.Column('author_raw', sa.String(), nullable=True),
    sa.Column('owner_raw', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('actual', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('author_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('kind', 'reg_number')
    )
    op.create_index(op.f('ix_patent_reg_number'), 'patent', ['reg_number'], unique=False)
    op.create_table('person',
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('tax_number', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('legal_address', sa.String(), nullable=True),
    sa.Column('fact_address', sa.String(), nullable=True),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tax_number')
    )
    op.create_index(op.f('ix_person_tax_number'), 'person', ['tax_number'], unique=True)
    op.create_table('ownership',
    sa.Column('patent_kind', sa.Integer(), nullable=False),
    sa.Column('patent_reg_number', sa.Integer(), nullable=False),
    sa.Column('person_tax_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patent_kind', 'patent_reg_number'], ['patent.kind', 'patent.reg_number'], ),
    sa.ForeignKeyConstraint(['person_tax_number'], ['person.tax_number'], ),
    sa.PrimaryKeyConstraint('patent_kind', 'patent_reg_number', 'person_tax_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ownership')
    op.drop_index(op.f('ix_person_tax_number'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_patent_reg_number'), table_name='patent')
    op.drop_table('patent')
    # ### end Alembic commands ###
