"""i love alembic

Revision ID: d3aeaddf7f9a
Revises: 
Create Date: 2024-06-16 14:50:37.583909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3aeaddf7f9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('filename', sa.String(length=1000), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('tax_numbers_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_id'), 'filter', ['id'], unique=False)
    op.create_table('patent',
    sa.Column('reg_number', sa.Integer(), nullable=False),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('appl_date', sa.Date(), nullable=True),
    sa.Column('author_raw', sa.String(), nullable=True),
    sa.Column('owner_raw', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('actual', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('author_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('kind', 'reg_number')
    )
    op.create_index(op.f('ix_patent_reg_number'), 'patent', ['reg_number'], unique=False)
    op.create_table('person',
    sa.Column('kind', sa.Integer(), nullable=False),
    sa.Column('tax_number', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('legal_address', sa.String(), nullable=True),
    sa.Column('fact_address', sa.String(), nullable=True),
    sa.Column('reg_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tax_number')
    )
    op.create_index(op.f('ix_person_tax_number'), 'person', ['tax_number'], unique=True)
    op.create_table('filtertaxnumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('tax_number', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filtertaxnumber_id'), 'filtertaxnumber', ['id'], unique=False)
    op.create_table('ownership',
    sa.Column('patent_kind', sa.Integer(), nullable=False),
    sa.Column('patent_reg_number', sa.Integer(), nullable=False),
    sa.Column('person_tax_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patent_kind', 'patent_reg_number'], ['patent.kind', 'patent.reg_number'], ),
    sa.ForeignKeyConstraint(['person_tax_number'], ['person.tax_number'], ),
    sa.PrimaryKeyConstraint('patent_kind', 'patent_reg_number', 'person_tax_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ownership')
    op.drop_index(op.f('ix_filtertaxnumber_id'), table_name='filtertaxnumber')
    op.drop_table('filtertaxnumber')
    op.drop_index(op.f('ix_person_tax_number'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_patent_reg_number'), table_name='patent')
    op.drop_table('patent')
    op.drop_index(op.f('ix_filter_id'), table_name='filter')
    op.drop_table('filter')
    # ### end Alembic commands ###
